TestWebApp/Models/Category.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebApp.Models;

public class Category
{
    [Key]
    public int CategoryId { get; set; }
    [Required]
    public string CategoryName { get; set; }

    [Required] 
    public bool Deleted { get; set; } = false;
    public ICollection<ProductCategory>? ProductCategories { get; set; }
}

TestWebApp/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace TestWebApp.Models;

public class Product
{
    [Key]
    public int ProductId { get; set; }
    [Required]
    public string ProductName { get; set; }
    [Required]
    public decimal UnitPrice { get; set; }
    [Required]
    public int UnitsInStock { get; set; }

    [Required] 
    public bool Deleted { get; set; } = false;
    
    public ICollection<ProductCategory>? ProductCategories { get; set; }
}

TestWebApp/Models/ProductCategory.cs
namespace TestWebApp.Models;

public class ProductCategory
{
    public int ProductId { get; set; }
    public Product? Product { get; set; }
    public int CategoryId { get; set; }
    public Category? Category { get; set; }
}

TestWebApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWebApp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

TestWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWebApp.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

TestWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TestWebApp.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

TestWebApp/Pages/Product/AddCategory.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TestWebApp.Data;
using TestWebApp.IRepository;
using TestWebApp.Models;

namespace TestWebApp.Pages.Product;

public class AddCategory : PageModel
{
    private ICategoryRepository _categoryRepository;
    private IProductRepository _productRepository;
    private IProductCategoryRepository _productCategoryRepository;
    public ICollection<Category> Categories { get; set; }
    public ICollection<Models.Product> Products { get; set; }
    
    public ProductCategory ProductCategory { get; set; }
    public AddCategory(ICategoryRepository categoryRepository, IProductRepository productRepository, IProductCategoryRepository productCategoryRepository)
    {
        _productCategoryRepository = productCategoryRepository;
        _categoryRepository = categoryRepository;
        _productRepository = productRepository;
    }
    public void OnGet()
    {
        Categories = _categoryRepository.GetCategories();
        Products = _productRepository.GetProducts();
    }

    public IActionResult OnPost(ProductCategory productCategory)
    {
        var product = _productRepository.GetProductById(productCategory.ProductId);
        var category = _categoryRepository.GetCategoryById(productCategory.CategoryId);
        
        if (product != null && category != null)
        {
            _productCategoryRepository.AddProductCategory(productCategory);
        }
        
        
        return RedirectToPage("Index");
    }
}

TestWebApp/Pages/Product/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TestWebApp.IRepository;
using TestWebApp.Models;

namespace TestWebApp.Pages.Product;

public class Create : PageModel
{
    private ICategoryRepository _categoryRepository;
    private IProductRepository _productRepository;
    public Models.Product Product { get; set; }
    public ICollection<Category> Categories { get; set; }
    public ICollection<Category> SelectedCategories { get; set; }
    public int ProductId { get; set; }

    public Create(ICategoryRepository categoryRepository, IProductRepository productRepository)
    {
        _categoryRepository = categoryRepository;
        _productRepository = productRepository;
    }
    
    public void OnGet()
    {
        ProductId = _productRepository.GetNextId();
        Categories = _categoryRepository.GetCategories();
    }

    public IActionResult OnPost(Models.Product product)
    {
        _productRepository.AddProduct(product);
        return RedirectToPage("Index");
    }
}

TestWebApp/Pages/Product/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TestWebApp.IRepository;
using TestWebApp.Models;

namespace TestWebApp.Pages.Product;

public class Index : PageModel
{
    private IProductRepository _productRepository;
    private IProductCategoryRepository _productCategoryRepository;
    public IEnumerable<Models.Product> Products;
    public ProductCategory ProductCategory { get; set; }
    public Index(IProductRepository productRepository, IProductCategoryRepository productCategoryRepository)
    {
        _productRepository = productRepository;
        _productCategoryRepository = productCategoryRepository;
    }
    public void OnGet()
    {
        Products = _productRepository.GetProducts().Where(x => x.Deleted==false);
        return;
    }

    public IActionResult OnPost(ProductCategory productCategory)
    {
        if (productCategory.ProductId != null && productCategory.CategoryId != null)
        {
            _productCategoryRepository.DeleteProductCategory(productCategory);
        }
        return RedirectToPage("Index");
    }
    
}

TestWebApp/Pages/Product/Update.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using TestWebApp.IRepository;
using TestWebApp.Models;

namespace TestWebApp.Pages.Product;

public class Update : PageModel
{
    
    private ICategoryRepository _categoryRepository;
    private IProductRepository _productRepository;
    public Models.Product Product { get; set; }
    public ICollection<Category> Categories { get; set; }
    public ICollection<Category> SelectedCategories { get; set; }
    public int ProductId { get; set; }

    public Update(ICategoryRepository categoryRepository, IProductRepository productRepository)
    {
        _categoryRepository = categoryRepository;
        _productRepository = productRepository;
    }
    
    public void OnGet(int id)
    {
        Product = _productRepository.GetProductById(id);
        Categories = _categoryRepository.GetCategories();
    }

    public IActionResult OnPostUpdate(Models.Product product)
    {
        _productRepository.UpdateProduct(product);
        return RedirectToPage("Index");
    }
    
    public IActionResult OnPostDelete(Models.Product product)
    {
        _productRepository.DeleteProduct(product.ProductId);
        return RedirectToPage("Index");
    }
}

TestWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TestWebApp/Pages/Product/AddCategory.cshtml
@page
@using TestWebApp.Models
@model TestWebApp.Pages.Product.AddCategory

@{
    Layout = "Shared/_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Product - Category</title>
</head>
<body>
<div>
    <form method="post">
        <select asp-for="ProductCategory.ProductId" class="form-select" aria-label="Default select example">
            @foreach (var product in @Model.Products)
            {
                <option value="@product.ProductId">@product.ProductName</option>
            }
        </select>
        <br/>
        <select asp-for="ProductCategory.CategoryId" class="form-select" aria-label="Default select example">
            @foreach (var cate in @Model.Categories)
            {
                <option value="@cate.CategoryId">@cate.CategoryName</option>
            }
        </select>
        <button type="submit" class="btn btn-primary" style="width: 150px"> Create</button>
    </form>

</div>
</body>
</html>

TestWebApp/Pages/Product/Create.cshtml
@page
@model TestWebApp.Pages.Product.Create

@{
    Layout = "Shared/_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Create new Product</title>
</head>
<body>
<form method="post">
    <input asp-for="Product.ProductId" type="hidden" value="@Model.ProductId"/>
    <div class="form-group">
        <label asp-for="Product.ProductName">Product name</label>
        <input asp-for="Product.ProductName" type="text" class="form-control" placeholder="name">
    </div>
    <div class="form-group">
        <label asp-for="Product.UnitPrice">Unit price</label>
        <input asp-for="Product.UnitPrice" class="form-control" placeholder="unit price">
    </div>
    <div class="form-group">
        <label asp-for="Product.UnitsInStock">Units in stock</label>
        <input asp-for="Product.UnitsInStock" class="form-control" placeholder="units in stock">
    </div>

    <button type="submit" class="btn btn-primary" style="width: 150px"> Create</button>
</form>
</body>
</html>

TestWebApp/Pages/Product/Index.cshtml
@page
@model TestWebApp.Pages.Product.Index

@{
    Layout = "Shared/_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Products</title>
</head>
<body>
<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Product List</h2>
        </div>
        <div class="col-6">

        </div>
    </div>

    <br/><br/>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Product Id</th>
            <th scope="col">Product Name</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Units In Stock</th>
            <th scope="col">Categories</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var product in Model.Products)
        {
            <tr>
                <th scope="row">@product.ProductId</th>
                <td>@product.ProductName</td>
                <td>@product.UnitPrice</td>
                <td>@product.UnitsInStock</td>
                <td>
                    @foreach (var cate in @product.ProductCategories)
                    {
                        @cate.Category.CategoryName
                        <form method="post">
                            <input asp-for="@Model.ProductCategory.ProductId" value="@product.ProductId" type="hidden"/>
                            <input asp-for="@Model.ProductCategory.CategoryId" value="@cate.CategoryId" type="hidden"/>
                            <button type="submit" class="btn-primary">Delete</button>
                        </form>
                        <br/>
                    }
                </td>
                <td>
                    <a href="/Product/Update/@product.ProductId" class="btn btn-primary">Edit</a>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <br/>
    <div class="col-6">
        <a asp-page="create" class="btn btn-primary">Create</a>
    </div>
    <br/>
    <div class="col-6">
        <a asp-page="addCategory" class="btn btn-primary">Add Category</a>
    </div>
</div>
</body>
</html>

TestWebApp/Pages/Product/Update.cshtml
@page "{id:int}"
@model TestWebApp.Pages.Product.Update

@{
    Layout = "Shared/_Layout";
}

<!DOCTYPE html>

<html>
<head>
    <title>Update Product</title>
</head>
<body>
<form method="post">
    <div class="form-group">
            <label asp-for="Product.ProductId">Product Id</label>
            <input asp-for="Product.ProductId" type="text" class="form-control" value="@Model.Product.ProductId" contenteditable="false">
        </div>
    <div class="form-group">
        <label asp-for="Product.ProductName">Product name</label>
        <input asp-for="Product.ProductName" type="text" class="form-control" value="@Model.Product.ProductName" placeholder="name">
    </div>
    <div class="form-group">
        <label asp-for="Product.UnitPrice">Unit price</label>
        <input asp-for="Product.UnitPrice" class="form-control" value="@Model.Product.UnitPrice" placeholder="unit price">
    </div>
    <div class="form-group">
        <label asp-for="Product.UnitsInStock">Units in stock</label>
        <input asp-for="Product.UnitsInStock" class="form-control" value="@Model.Product.UnitsInStock" placeholder="units in stock">
    </div>

    <button type="submit" class="btn btn-primary" style="width: 150px" asp-page-handler="Update"> Update</button>
    <button type="submit" class="btn btn-danger" style="width: 150px"  asp-page-handler="Delete"> Delete</button>
</form>
</body>
</html>

TestWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - TestWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TestWebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">TestWebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark"  asp-page="Product/Index">Product Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="Category/Index">Category Page</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - TestWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>